### ISSUE TITLE
Problem "Cancel on Next Payment Date" and "Multiple Memberships per User"

### ISSUE THREAD

**Issue by mmieszalski** [strangerstudios/pmpro-cancel-on-next-payment-date#17]
When using the "Cancel on Next Payment Date" and "Multiple Memberships per User" plugins, the user who cancels subscriptions for two groups causes displaying the end date for one product from the group, the other group disconnects immediately completely.

**Comment by ideadude** [comment]
It's possible our skip-cancel branch/fix fixes this issue. I will do some testing to see if that is the case and if not, if we can address this issue in another way for MMPU support.

**Comment by mmieszalski** [comment]
I hope it will work ;)

**Comment by ideadude** [comment]
The latest versions seem to be working well with MMPU. Closing this issue, but if you are having trouble, please open again for as much information as possible to recreate. Thanks.
