### ISSUE TITLE
Date in cancellation text not localized.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-cancel-on-next-payment-date#28]
**Describe the bug**
If you translate the confirm Message of the pmpro-cancel-on-next-payment-date plugin, the Date will not be translated in the local language:

English:
Your recurring subscription has been cancelled. Your active membership will expire on %s.

German Translation:
Deine Membership wurde gekündigt. Deine aktive Membership endet am 1. January 2022.

The Date still is in English with “January” instead of German “Januar”.

**To Reproduce**
1. Go to Settings > General and set the Site Language option to Deutsch and save settings
2. In a private/incognito browser window log in as a user that is subscribed to a recurring membership level.
3. Navigate to the Membership Account page and click on the link to cancel the membership subscription.
4. Confirm cancellation.
5. Observe that the date is still in English instead of the set site language.

**Expected behavior**
The cancellation text should show the i18n date.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by michaelbeil** [comment]
@ideadude this [PR](https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/pull/29/files) was closed, so the [cancellation text string](https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/blob/dev/pmpro-cancel-on-next-payment-date.php#L213) didn’t get internationalization for the date.
