### ISSUE TITLE
PHP Notice: Undefined index from on line 47

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-cancel-on-next-payment-date#38]
**Describe the bug**
Getting a notice for an undefined index on line 47 of the main plugin file.

**To Reproduce**
1. Go to Membership > Settings > Levels
2. Delete a level.
3. See warning

**Screenshots**
<img width="1135" alt="Screen Shot 2022-05-05 at 6 22 36 AM" src="https://user-images.githubusercontent.com/5312875/166905422-5a77ef6e-41eb-45fa-a7ef-fece559d8d6f.png">

**Comment by mircobabini** [comment]
There's a fix for this: https://github.com/strangerstudios/pmpro-cancel-on-next-payment-date/pull/30
